testa:teste.o
	gcc -o testa testa.o
teste.o:testa.c arvores.h
	gcc -O -c testa.c
#testa2:testa2.o
#	gcc -o testa2 testa2.o
#teste2.o:testa2.c arvores_binarias.h
#	gcc -O -c testa2.c
clean:
	rm -f testa*
